name = "ExamplePackage"
uuid = "4be654c0-eb74-11e8-1620-b5e399e31a97"
authors = ["anubhavpcjha <anubhavpcjha@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
